services:

  cache-redis:
    image: redis:latest
    container_name:  cache-redis
    restart: always
    ports:
      - 6379:6379  
    networks:
      - app-network

  database-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd"
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: 1433
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    networks:
      - app-network

  chatservice:
    image: ${DOCKER_REGISTRY-}chatservice
    build:
      context: .
      dockerfile: ChatService/Dockerfile
    ports:
      - 5230:8080
      - 5231:8081
    networks:
      - app-network
    depends_on:
      - database-mssql
      - cache-redis

networks:
  app-network:
    driver: bridge